# Generated by Django 3.2.19 on 2023-06-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_recipe_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
